=== chenhijy/pankmer_operations/schema/anchorRegionConfig.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "",
    "required": [
        "indexes",
        "anchorAssembly",
        "outdir"
    ],
    "properties": {
        "indexes":  {
            "type": "array",
            "items": {
                "type": "string"
            },  
            "description": "a list of paths to indexes to anchor"
        },
        "anchorAssembly":  {
            "type": "string",
            "description": "path to fasta file for the anchor/reference assembly"
        },
        "anchorAsmChromList": {
            "type": "array",
            "items": {
                "type": "string"
            },  
            "description": "a list anchor asm chrom names",
            "default": ["Chr01","Chr02","Chr03","Chr04","Chr05","Chr06","Chr07","Chr08","Chr09","Chr10","Chr11","Chr12","Chr13","Chr14","Chr15","Chr16","Chr17","Chr18","Chr19","Chr20"]
        },
        "outdir":  {
            "type": "string",
            "description": "outdir path"
        },
        "uniqueID":{
            "type": "string",
            "description": "unique modifier",
            "default": ""
        },
        "threads": {
            "type": "integer",
            "description": "the number of threads to use for mapping",
            "default": 32
        }
    }
}

=== chenhijy/pankmer_operations/config/anchorMaturityGroups.json
{
    "outdir": "pankmer/maturityGroupAnalysis2_41002",
    "uniqueID": "241003",
    "indexes": ["pankmer/maturityGroupAnalysis2_41002/15_MaturityGrpV_index.tar",
                "pankmer/maturityGroupAnalysis2_41002/17_MaturityGrpIII_index.tar",
                "pankmer/maturityGroupAnalysis2_41002/21_MaturityGrpIV_index.tar",
                "pankmer/maturityGroupAnalysis2_41002/4_MaturityGrpVIIandVIII_index.tar",
                "pankmer/maturityGroupAnalysis2_41002/5_MaturityGrpVI_index.tar",
                "pankmer/maturityGroupAnalysis2_41002/8_MaturityGrp0and00_index.tar",
                "pankmer/maturityGroupAnalysis2_41002/8_MaturityGrpIandII_index.tar"],
    "anchorAssembly": "assemblies/FINAL/Gsoj_PI483463.a01.softmasked.fasta.gz"
}
